name: Cloud project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
        # Checks out the repository
      - name: Checkout repository
        uses: actions/checkout@v4

        # Sets up Python using the version we use (3.11)
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

        # Installs required dependencies (in the requirements.txt file)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r api/requirements.txt

        # Runs the tests using pytest
      - name: Pytest
        run: pytest
        working-directory: ./api